In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Creation

In [3]:
data=[[1,2],[3,4]]
t=torch.tensor(data)

In [4]:
print(t)

tensor([[1, 2],
        [3, 4]])


In [5]:
nx=np.array(data)
t2=torch.tensor(nx)

In [6]:
tr=torch.rand(4,5)
tr

tensor([[0.6746, 0.2950, 0.5120, 0.5120, 0.5774],
        [0.5969, 0.9735, 0.0695, 0.3126, 0.8719],
        [0.6879, 0.8408, 0.6352, 0.2715, 0.3381],
        [0.8078, 0.8872, 0.8157, 0.1493, 0.7016]])

Characterstics

In [8]:
print(t.shape)
print(t.dtype)
print(t.device)

torch.Size([2, 2])
torch.int64
cpu


Basic operations

In [17]:
print(tr[0])
print(tr[0:2])
print(tr[0][0:3])

#Concatentaion
print(torch.cat([t,t2]))#basically adds over it

#transpose
print(tr.T)


tensor([0.6746, 0.2950, 0.5120, 0.5120, 0.5774])
tensor([[0.6746, 0.2950, 0.5120, 0.5120, 0.5774],
        [0.5969, 0.9735, 0.0695, 0.3126, 0.8719]])
tensor([0.6746, 0.2950, 0.5120])
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])
tensor([[0.6746, 0.5969, 0.6879, 0.8078],
        [0.2950, 0.9735, 0.8408, 0.8872],
        [0.5120, 0.0695, 0.6352, 0.8157],
        [0.5120, 0.3126, 0.2715, 0.1493],
        [0.5774, 0.8719, 0.3381, 0.7016]])


In [20]:
#sum of all
agg=tr.sum()
print(agg)

tensor(11.5307)


In [23]:
#conversion to float
print(agg.item())

11.53072738647461


In [24]:
#adding to each element
tr.add_(5)
tr

tensor([[5.6746, 5.2950, 5.5120, 5.5120, 5.5774],
        [5.5969, 5.9735, 5.0695, 5.3126, 5.8719],
        [5.6879, 5.8408, 5.6352, 5.2715, 5.3381],
        [5.8078, 5.8872, 5.8157, 5.1493, 5.7016]])

In [25]:
n=tr.numpy()
#now they will store same memory location and change in one will reflect in other
n[0][0]=5
print(tr)

tensor([[5.0000, 5.2950, 5.5120, 5.5120, 5.5774],
        [5.5969, 5.9735, 5.0695, 5.3126, 5.8719],
        [5.6879, 5.8408, 5.6352, 5.2715, 5.3381],
        [5.8078, 5.8872, 5.8157, 5.1493, 5.7016]])
